# Generated by Django 5.2.16 on 2026-07-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "code",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=250)),
                ("super_code", models.CharField(blank=True, max_length=5, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("place", models.CharField(blank=True, max_length=60, null=True)),
                ("city", models.CharField(blank=True, max_length=80, null=True)),
                ("state", models.CharField(blank=True, max_length=40, null=True)),
                ("phone", models.CharField(blank=True, max_length=60, null=True)),
                ("phone2", models.CharField(blank=True, max_length=60, null=True)),
                ("fax", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "remarkcolumntitle",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("area", models.CharField(blank=True, max_length=30, null=True)),
                ("gstin", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "acc_master",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "code",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "size",
                    models.CharField(
                        blank=True, db_column="text3", max_length=60, null=True
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        blank=True, db_column="text5", max_length=60, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=10, null=True)),
                ("taxcode", models.CharField(blank=True, max_length=5, null=True)),
                ("company", models.CharField(blank=True, max_length=30, null=True)),
                ("product", models.CharField(blank=True, max_length=30, null=True)),
                ("brand", models.CharField(blank=True, max_length=30, null=True)),
                ("text6", models.CharField(blank=True, max_length=40, null=True)),
                ("nameinsl", models.CharField(blank=True, max_length=350, null=True)),
                ("settings", models.CharField(blank=True, max_length=300, null=True)),
                ("properties", models.CharField(blank=True, max_length=900, null=True)),
            ],
            options={
                "db_table": "acc_product",
            },
        ),
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                ("slno", models.AutoField(primary_key=True, serialize=False)),
                ("productcode", models.CharField(max_length=30)),
                (
                    "salesprice",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "secondprice",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "thirdprice",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "fourthprice",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "nlc1",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                ("barcode", models.CharField(blank=True, max_length=35, null=True)),
                (
                    "bmrp",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                ("settings", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "db_table": "acc_productbatch",
            },
        ),
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("settings", models.CharField(blank=True, max_length=300, null=True)),
                ("url", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "db_table": "acc_productbrand",
            },
        ),
        migrations.CreateModel(
            name="ProductPhoto",
            fields=[
                ("slno", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(blank=True, max_length=30, null=True)),
                ("url2", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "db_table": "acc_productphoto",
            },
        ),
        migrations.CreateModel(
            name="ProductProduct",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("settings", models.CharField(blank=True, max_length=300, null=True)),
                ("url", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "db_table": "acc_productproduct",
            },
        ),
        migrations.CreateModel(
            name="ServiceMaster",
            fields=[
                ("slno", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("code", models.CharField(blank=True, max_length=30, null=True)),
                ("url", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "db_table": "acc_tt_servicemaster",
            },
        ),
    ]
