# Generated by Django 5.2.16 on 2026-07-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_column="id", max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(db_column="pass", max_length=100)),
                ("role", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "acc_users",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="master",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="productbatch",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="productbrand",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="productphoto",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="productproduct",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="servicemaster",
            options={"managed": False},
        ),
    ]
